### ISSUE TITLE
One-step Script path error

### ISSUE THREAD

**Issue by silver886** [filebrowser/filebrowser.github.io#4] opened 2018-04-02 12:55 UTC
**Operating system**: Debian - 9 (stretch)

The path that binary file located is `/usr/local/bin` instead of `/user/local/bin`

**Comment by 1138-4EB** [comment] 2018-07-27 22:40
Closing because `/user/local/bin` is not found in [`get.sh`](https://github.com/filebrowser/filebrowser.github.io/blob/master/get.sh). Cannot reproduce.

Please reopen if you are still having issues with the script.

**Closed by 1138-4EB** 2018-07-27 22:40 UTC
